project_name: kubebuilder-initializer-plugin

before:
  hooks:
    - go mod download

builds:
  - <<: &build_defaults
      env:
        - CGO_ENABLED=0
      ldflags: null
      main: ./cmd
      mod_timestamp: '{{ .CommitTimestamp }}'

  - <<: *build_defaults
    id: macos
    goos: [darwin]
    goarch: [amd64, arm64]

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [386, arm, amd64, arm64]

  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [amd64, arm64]

  - <<: *build_defaults
    id: freebsd
    goos: [freebsd]
    goarch: [386, amd64]


checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS'
  algorithm: sha256

archives:
  - <<: &archives_defaults
      files:
        - README.md
        - LICENSE
    id: nix
    builds: [macos, linux]
    format: tar.gz
  - <<: *archives_defaults
    id: windows
    builds: [windows]
    format: zip

changelog:
  skip: true

release:
  github:
    owner: astrokube
    name: kubebuilder-initializer-plugin

brews:
  - name: kubebuilder-initializer-plugin
    homepage: https://github.com/astrokube/homebrew-tools
    tap:
      owner: astrokube
      name: homebrew-tools
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"