project_name: kubebuilder-initializer-plugin
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    mod_timestamp: '{{ .CommitTimestamp }}'

checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS'
  algorithm: sha256

archives:
  - format_overrides:
      - goos: windows
        format: zip

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - typo
      - (?i)foo

release:
  name_template: "{{.ProjectName}} v{{.Version}}"
  github:
    owner: astrokube
    name: kubebuilder-initializer-plugin
  draft: true
  prerelease: auto
  header: |
    ## New release ({{ .Date }})
    Welcome to this new release!
  footer: |
    ## Thanks!
    Those were the changes on {{ .Tag }}!

brews:
  - name: kubebuilder-initializer-plugin
    homepage: https://github.com/astrokube/homebrew-tools
    tap:
      owner: astrokube
      name: homebrew-tools
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"