name: Release Drafter

on:
  push:
    branches: [ "main" ]

jobs:

  releaseDrafter:
    runs-on: ubuntu-latest
    steps:
      - name: Run release-drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}